# coding: utf-8

"""
    Tpay.com Technical Documentation

     <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>  # noqa: E501

    The version of the OpenAPI document: 1.1.2
    Contact: pt@tpay.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class MasspaymentCreateResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'result': 'Result',
        'sum': 'float',
        'count': 'int',
        'pack_id': 'int',
        'referers': 'str',
        'error': 'MasspaymentErrCode',
        'desc': 'MasspaymentErrDesc'
    }

    attribute_map = {
        'result': 'result',
        'sum': 'sum',
        'count': 'count',
        'pack_id': 'pack_id',
        'referers': 'referers',
        'error': 'error',
        'desc': 'desc'
    }

    def __init__(self, result=None, sum=None, count=None, pack_id=None, referers=None, error=None, desc=None, local_vars_configuration=None):  # noqa: E501
        """MasspaymentCreateResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._result = None
        self._sum = None
        self._count = None
        self._pack_id = None
        self._referers = None
        self._error = None
        self._desc = None
        self.discriminator = None

        if result is not None:
            self.result = result
        if sum is not None:
            self.sum = sum
        if count is not None:
            self.count = count
        if pack_id is not None:
            self.pack_id = pack_id
        if referers is not None:
            self.referers = referers
        if error is not None:
            self.error = error
        if desc is not None:
            self.desc = desc

    @property
    def result(self):
        """Gets the result of this MasspaymentCreateResponse.  # noqa: E501


        :return: The result of this MasspaymentCreateResponse.  # noqa: E501
        :rtype: Result
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this MasspaymentCreateResponse.


        :param result: The result of this MasspaymentCreateResponse.  # noqa: E501
        :type: Result
        """

        self._result = result

    @property
    def sum(self):
        """Gets the sum of this MasspaymentCreateResponse.  # noqa: E501

        Sum of transfers in the package  # noqa: E501

        :return: The sum of this MasspaymentCreateResponse.  # noqa: E501
        :rtype: float
        """
        return self._sum

    @sum.setter
    def sum(self, sum):
        """Sets the sum of this MasspaymentCreateResponse.

        Sum of transfers in the package  # noqa: E501

        :param sum: The sum of this MasspaymentCreateResponse.  # noqa: E501
        :type: float
        """

        self._sum = sum

    @property
    def count(self):
        """Gets the count of this MasspaymentCreateResponse.  # noqa: E501

        Number of transfers defined in CSV file  # noqa: E501

        :return: The count of this MasspaymentCreateResponse.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this MasspaymentCreateResponse.

        Number of transfers defined in CSV file  # noqa: E501

        :param count: The count of this MasspaymentCreateResponse.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def pack_id(self):
        """Gets the pack_id of this MasspaymentCreateResponse.  # noqa: E501

        ID of created pack using method create.  # noqa: E501

        :return: The pack_id of this MasspaymentCreateResponse.  # noqa: E501
        :rtype: int
        """
        return self._pack_id

    @pack_id.setter
    def pack_id(self, pack_id):
        """Sets the pack_id of this MasspaymentCreateResponse.

        ID of created pack using method create.  # noqa: E501

        :param pack_id: The pack_id of this MasspaymentCreateResponse.  # noqa: E501
        :type: int
        """

        self._pack_id = pack_id

    @property
    def referers(self):
        """Gets the referers of this MasspaymentCreateResponse.  # noqa: E501

        Field visible if transfersID has been sent (see chap. \"Exemplary CSV file\") in JSON format as following: ID in transfer : ID of transfers in tpay.com system. This allows tracking single transfers.   # noqa: E501

        :return: The referers of this MasspaymentCreateResponse.  # noqa: E501
        :rtype: str
        """
        return self._referers

    @referers.setter
    def referers(self, referers):
        """Sets the referers of this MasspaymentCreateResponse.

        Field visible if transfersID has been sent (see chap. \"Exemplary CSV file\") in JSON format as following: ID in transfer : ID of transfers in tpay.com system. This allows tracking single transfers.   # noqa: E501

        :param referers: The referers of this MasspaymentCreateResponse.  # noqa: E501
        :type: str
        """

        self._referers = referers

    @property
    def error(self):
        """Gets the error of this MasspaymentCreateResponse.  # noqa: E501


        :return: The error of this MasspaymentCreateResponse.  # noqa: E501
        :rtype: MasspaymentErrCode
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this MasspaymentCreateResponse.


        :param error: The error of this MasspaymentCreateResponse.  # noqa: E501
        :type: MasspaymentErrCode
        """

        self._error = error

    @property
    def desc(self):
        """Gets the desc of this MasspaymentCreateResponse.  # noqa: E501


        :return: The desc of this MasspaymentCreateResponse.  # noqa: E501
        :rtype: MasspaymentErrDesc
        """
        return self._desc

    @desc.setter
    def desc(self, desc):
        """Sets the desc of this MasspaymentCreateResponse.


        :param desc: The desc of this MasspaymentCreateResponse.  # noqa: E501
        :type: MasspaymentErrDesc
        """

        self._desc = desc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MasspaymentCreateResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MasspaymentCreateResponse):
            return True

        return self.to_dict() != other.to_dict()
