# coding: utf-8

# flake8: noqa

"""
    Tpay.com Technical Documentation

     <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>  # noqa: E501

    The version of the OpenAPI document: 1.1.2
    Contact: pt@tpay.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.cards_api_api import CardsAPIApi
from openapi_client.api.masspayments_api import MasspaymentsApi
from openapi_client.api.registration_api import RegistrationApi
from openapi_client.api.transaction_api_api import TransactionAPIApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.api_data_object import ApiDataObject
from openapi_client.models.blik_alias import BlikAlias
from openapi_client.models.blik_alias_response import BlikAliasResponse
from openapi_client.models.blik_fields import BlikFields
from openapi_client.models.blik_response import BlikResponse
from openapi_client.models.branch_object import BranchObject
from openapi_client.models.cards_err_code import CardsErrCode
from openapi_client.models.chargeback_status import ChargebackStatus
from openapi_client.models.check_fields import CheckFields
from openapi_client.models.check_response import CheckResponse
from openapi_client.models.create_fields import CreateFields
from openapi_client.models.create_response import CreateResponse
from openapi_client.models.deregister_fields import DeregisterFields
from openapi_client.models.get_fields import GetFields
from openapi_client.models.get_response import GetResponse
from openapi_client.models.language import Language
from openapi_client.models.legal_form_object import LegalFormObject
from openapi_client.models.masspayment_authorize_fields import MasspaymentAuthorizeFields
from openapi_client.models.masspayment_authorize_response import MasspaymentAuthorizeResponse
from openapi_client.models.masspayment_create_fields import MasspaymentCreateFields
from openapi_client.models.masspayment_create_response import MasspaymentCreateResponse
from openapi_client.models.masspayment_err_code import MasspaymentErrCode
from openapi_client.models.masspayment_err_desc import MasspaymentErrDesc
from openapi_client.models.masspayment_packs_fields import MasspaymentPacksFields
from openapi_client.models.masspayment_packs_response import MasspaymentPacksResponse
from openapi_client.models.masspayment_transfers_fields import MasspaymentTransfersFields
from openapi_client.models.masspayment_transfers_response import MasspaymentTransfersResponse
from openapi_client.models.onetimer import Onetimer
from openapi_client.models.packs_object import PacksObject
from openapi_client.models.presale_fields import PresaleFields
from openapi_client.models.refund_any_fields import RefundAnyFields
from openapi_client.models.refund_any_response import RefundAnyResponse
from openapi_client.models.refund_fields import RefundFields
from openapi_client.models.refund_response import RefundResponse
from openapi_client.models.refund_status_response import RefundStatusResponse
from openapi_client.models.refund_transaction_fields import RefundTransactionFields
from openapi_client.models.register_fields import RegisterFields
from openapi_client.models.register_sale_fields import RegisterSaleFields
from openapi_client.models.register_sale_response import RegisterSaleResponse
from openapi_client.models.registration_err_codes import RegistrationErrCodes
from openapi_client.models.registration_input_fields import RegistrationInputFields
from openapi_client.models.registration_inputs_response import RegistrationInputsResponse
from openapi_client.models.registration_register_response import RegistrationRegisterResponse
from openapi_client.models.report_fields import ReportFields
from openapi_client.models.report_response import ReportResponse
from openapi_client.models.result import Result
from openapi_client.models.sale_fields import SaleFields
from openapi_client.models.sale_response import SaleResponse
from openapi_client.models.securesale_fields import SecuresaleFields
from openapi_client.models.securesale_response import SecuresaleResponse
from openapi_client.models.seller_data_object import SellerDataObject
from openapi_client.models.transaction_error_codes import TransactionErrorCodes
from openapi_client.models.transfers_object import TransfersObject
from openapi_client.models.vc_finish_fields import VcFinishFields
from openapi_client.models.vc_finish_request_example import VcFinishRequestExample
from openapi_client.models.vc_prepare_fields import VcPrepareFields
from openapi_client.models.vc_prepare_response import VcPrepareResponse
from openapi_client.models.vc_prepare_response_example import VcPrepareResponseExample

